name: confidentz
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - colorama=0.4.6
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pywin32=305
  - pyzmq=25.0.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - cachetools==5.3.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.12.0
      - flatbuffers==23.5.9
      - fonttools==4.39.4
      - gast==0.4.0
      - gdown==4.7.1
      - google-auth==2.18.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - idna==3.4
      - jax==0.4.10
      - keras==2.12.0
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - ml-dtypes==0.1.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pillow==9.5.0
      - protobuf==4.23.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - soupsieve==2.4.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-hub==0.13.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - tqdm==4.65.0
      - typing-extensions==4.6.2
      - urllib3==1.26.16
      - werkzeug==2.3.4
      - wrapt==1.14.1
