name: base
channels:
  - defaults
dependencies:
  - anaconda-client=1.11.1
  - anaconda-navigator=2.4.0
  - anaconda-project=0.11.1
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.12.2
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - clyent=1.2.2
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.5.0
  - conda-build=3.23.3
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - conda-repo-cli=1.0.41
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - filelock=3.9.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - krb5=1.19.4
  - lerc=3.0
  - libarchive=3.6.2
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - liblief=0.12.3
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - menuinst=1.4.19
  - msys2-conda-epoch=20160418
  - navigator-updater=0.3.0
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pathlib=1.0.1
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - pytz=2022.7
  - pywin32=305
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.29.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2023c
  - ujson=5.4.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - flatbuffers==23.5.9
      - gast==0.4.0
      - google-auth==2.18.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - jax==0.4.10
      - keras==2.12.0
      - libclang==16.0.0
      - markdown==3.4.3
      - ml-dtypes==0.1.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pip==23.1.2
      - protobuf==4.23.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-hub==0.13.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - typing-extensions==4.6.1
      - werkzeug==2.3.4
      - wrapt==1.14.1
